### PR TITLE
(feat) KHP3-7060 : Add initializer configs for OpenMRS ID and payment modes

### PR DESCRIPTION
**Pull request by donaldkibet**
### Description

This adds config to enable registration and waiver to work correctly

cc @ojwanganto @makombe @PatrickWaweru @patryllus will need this PR https://github.com/mekomsolutions/openmrs-module-initializer/pull/269 for supporting billing domain work

### CODE REVIEW

**Comment by donaldkibet** [comment]
Using the initializer to try update **OpenMRS** identifier sources results in addition of another Identifier. @palladiumkenya/qa we might need to do a raw query to update this.

**Comment by donaldkibet** [comment]
cc @andrineM ☝🏽

**Review by Murithijoshua — APPROVED** [review]

**Comment by ojwanganto** [comment]
> Using the initializer to try update **OpenMRS** identifier sources results in addition of another Identifier. @palladiumkenya/qa we might need to do a raw query to update this. Screenshot 2024-11-11 at 16 07 23

I think we can easily get this done using raw sql. Alternatively, we can use liquibase for the raw sql and have a sure way of making the change

**Comment by makombe** [comment]
> Using the initializer to try update **OpenMRS** identifier sources results in addition of another Identifier. @palladiumkenya/qa we might need to do a raw query to update this. Screenshot 2024-11-11 at 16 07 23

@donaldkibet Do you want to update the PR to exclude the csv forOpenMRS ID ?

**Comment by donaldkibet** [comment]
@makombe excluded the auto-generation option. cc @palladiumkenya/qa will need script to update **OpenMRSID** manual entry to false

**Review by makombe — APPROVED** [review]
Thanks @donaldkibet

**Pull request merged**
