### PR TITLE
Update Clinical Encounter Form

### PR DESCRIPTION
**Pull request by mmatheka**
Update Clinical Encounter Form to add cause of death and change children death to family  member deaths

### CODE REVIEW

**Comment by donaldkibet** [comment]
Thanks @mmatheka please fix the conflicts

**Comment by makombe** [comment]
I think @mmatheka  you might need to close this and do a fresh PR with only clinical encounter form.

**Comment by donaldkibet** [comment]
@mmatheka do we want to merge revised tools to main. Also agree with @makombe, would be nice to rebase these on master and then we can proceed.

**Comment by donaldkibet** [comment]
This PR is too big, we can effectively provide review on it. Please submit individual PR for each form update

**Pull request closed without merging**
