### PR TITLE
Update HTS_Eligibility_Screening_Revised.json Risk Score and Category

### PR DESCRIPTION
**Pull request by ckote**
Concepts changed to match 2.X risk score and category UUIDs

### CODE REVIEW

**Review by RAJABIBRAZ — APPROVED** [review]
hope this two are the only changes..

**Review by njorocs — CHANGES_REQUESTED** [review]
@ckote , please make the following changes to the risk category answers.

1407AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - "Low"
1408AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - "High"

**Comment by ckote** [comment]
@njorocs and @patryllus This is done. @andrineM

**Review by njorocs — APPROVED** [review]
lgtm

**Pull request merged**
