### PR TITLE
Update HTS_Eligibility_Screening.json

### PR DESCRIPTION
**Pull request by Murithijoshua**
Revert changes from PR #701 

This pull request reverts the changes implemented in PR #701 , which was authored by @PatrickWaweru 

Reason: QA team requested need for changes made

### CODE REVIEW

**Review by PatrickWaweru — CHANGES_REQUESTED** [review]
This is NOT approved

**Review by donaldkibet — CHANGES_REQUESTED** [review]
cc @andrineM @Murithijoshua @RAJABIBRAZ see Waweru comments

**Comment by PatrickWaweru** [comment]
@makombe  This is NOT approved because there are only two changes made in the PR. For pregnant and breastfeeding declined to answer. These are required for ML to work correctly. This change cannot be reverted as it is a requirement for ML. The PR that needs to be reverted is https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/702 which breaks ML.

**Comment by Murithijoshua** [comment]
@PatrickWaweru the PR #702 introduces the revised population types, unfortunately our ML model wasn't trained with it, this is as advised by @chesterosoronyas however PR #701 has correct populations plus the 2 variables you added which are necessary as you started:
**tl:tr** Revised tools population types ain't trained yet, hence need for revert

> @makombe This is NOT approved because there are only two changes made in the PR. For pregnant and breastfeeding declined to answer. These are required for ML to work correctly. This change cannot be reverted as it is a requirement for ML. The PR that needs to be reverted is #702 which breaks ML.

**Comment by PatrickWaweru** [comment]
@Murithijoshua Yes but you want to revert https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/701. What we want is https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/702 reverted.

**Comment by Murithijoshua** [comment]
@PatrickWaweru Yes correct ! Seems my English is a problem here..
Tunataka tutumie change is done by  #701.

**Comment by PatrickWaweru** [comment]
@Murithijoshua Ok. To do that, create a new PR to revert the https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/702   i.e 
1. fork the repo. 
2. Pull latest main branch
3. Use git revert 6f4fa1a407feb40f3e6f94e6d3b62fb7896ffe58 (i.e the commit that introduced the change)
4. git commit -m "Revert for PR 702"
5. git push origin yourbranch
6. Do a new PR from there

**Pull request closed without merging**
