### PR TITLE
Update VMMC_Medical_History_and_Physical_Examination.json

### PR DESCRIPTION
**Pull request by ckote**
solved issue of unable to save and boolean concepts

### CODE REVIEW

**Review by makombe — APPROVED** [review]
Thanks @ckote

**Comment by makombe** [comment]
@ckote How did you handle the boolean? are you able to point to me one of the question which had boolean.

**Comment by ckote** [comment]
Here's a snippet:

{
                  "label": "Consent given?",
                  "type": "obs",
                  "id": "consentGiven",
                  "required": "true",
                  "questionOptions": {
                    "concept": "1710AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                    "rendering": "radio",
                    "answers": [
                      {
                        "concept": "true",
                        "label": "Yes"
                      },
                      {
                        "concept": "false",
                        "label": "No"
                      }
                    ]
                  },
                  "hide": {
                    "hideWhenExpression": "age < 18 || sex !== 'M'"
                  }
                },
{
                  "label": "Client presenting with complaint:",
                  "type": "obs",
                  "id": "ClientPreseNtComplainT",
                  "required": "true",
                  "questionOptions": {
                    "concept": "1154AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                    "rendering": "select",
                    "answers": [
                        {
                            "concept": "true",
                            "label": "Yes"
                        },
                        {
                            "concept": "false",
                            "label": "No"
                        }
                    ]
                },
                  "hide": {
                    "hideWhenExpression": "consentGiven !== 'true' && assentGiven !== '1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'"
                  }
                },
{
                      "label": "Client has any known allergie(s)?  ",
                      "type": "obs",
                      "id": "KnoWnAllerg",
                      "required": "true",
                      "questionOptions": {
                        "concept": "160557AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                        "rendering": "radio",
                        "answers": [
                            {
                                "concept": "true",
                                "label": "Yes"
                            },
                            {
                                "concept": "false",
                                "label": "No"
                            }
                        ]
                      },
                      "hide": {
                        "hideWhenExpression": "consentGiven !== 'true' && assentGiven !== '1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'"
                      }
                    }
                    
There were only 3 questions

**Comment by ckote** [comment]
Also I'm realising as the community is releasing new concepts and replacing what was there before we might be in trouble if some are changed to boolean after merging the community updates for concepts

**Comment by ckote** [comment]
@makombe

**Comment by makombe** [comment]
> Here's a snippet:
> 
> { "label": "Consent given?", "type": "obs", "id": "consentGiven", "required": "true", "questionOptions": { "concept": "1710AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "rendering": "radio", "answers": [ { "concept": "true", "label": "Yes" }, { "concept": "false", "label": "No" } ] }, "hide": { "hideWhenExpression": "age < 18 || sex !== 'M'" } }, { "label": "Client presenting with complaint:", "type": "obs", "id": "ClientPreseNtComplainT", "required": "true", "questionOptions": { "concept": "1154AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "rendering": "select", "answers": [ { "concept": "true", "label": "Yes" }, { "concept": "false", "label": "No" } ] }, "hide": { "hideWhenExpression": "consentGiven !== 'true' && assentGiven !== '1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'" } }, { "label": "Client has any known allergie(s)? ", "type": "obs", "id": "KnoWnAllerg", "required": "true", "questionOptions": { "concept": "160557AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "rendering": "radio", "answers": [ { "concept": "true", "label": "Yes" }, { "concept": "false", "label": "No" } ] }, "hide": { "hideWhenExpression": "consentGiven !== 'true' && assentGiven !== '1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'" } }
> 
> There were only 3 questions

Thanks @ckote. The boolean should now work correctly

**Pull request merged**
