### PR TITLE
(chore) update dev-config.json and staging-config.json for seemless deployment

### PR DESCRIPTION
**Pull request by its-kios09**

### CODE REVIEW

**Review by ojwanganto — APPROVED** [review]

**Comment by ojwanganto** [comment]
I don't know why I see 0 files changed

**Comment by makombe** [comment]
@its-kios09 I see you have reverted the change, does this PR still make sense ?

**Review by makombe — CHANGES_REQUESTED** [review]
Seems changes are reverted

**Comment by donaldkibet** [comment]
@its-kios09 seem to have reverted the changes. Closing this branch.

**Pull request closed without merging**
