### PR TITLE
(feat) Add validation for registration page field

### PR DESCRIPTION
**Pull request by donaldkibet**
## Description

This PR adds validation for the following patient registration form.
- location
- Sub-location
- Landmark
- Nearest land mark
- phone number, adding regex for correct phone number format

This is in response to reported field feedback issue 1 as listed in this [document](https://palladiumgroup.sharepoint.com/:x:/r/sites/KeHMISII/_layouts/15/Doc.aspx?sourcedoc=%7B50D0A01B-3B47-4AB3-B178-F6C4BA95CE68%7D&file=03%20Missing%20functionalities%20and%20key%20enhancements.xlsx&fromShare=true&action=default&mobileredirect=true)

cc @mmatheka

## Screensho
https://github.com/palladiumkenya/openmrs-config-kenyaemr/assets/28008754/131764fe-6b05-4328-9948-fda645794e33

t

### CODE REVIEW

**Comment by ojwanganto** [comment]
Should we make all of the configured fields required?

**Comment by donaldkibet** [comment]
Most of the other fields are already configured to work that way e.g `inbuilt` and `obs`. The `address`, `person attributes` and the `phone` field was the remaining bit, which this PR attempts to fix.

**Comment by ojwanganto** [comment]
I think we are good for now. We can consult on which fields should be mandatory, now that we are going facility-wide

**Review by ojwanganto — APPROVED** [review]

**Comment by donaldkibet** [comment]
Thanks @ojwanganto, this PR is also related to this [PR](https://github.com/openmrs/openmrs-esm-patient-management/pull/1030)

**Pull request merged**
