### PR TITLE
Ability to add new facility/locations

### PR DESCRIPTION
**Pull request by makombe**
Screenshot from 2024-09-04 15-43-33

### CODE REVIEW

**Review by patryllus — APPROVED** [review]
Looks okay. Thanks @makombe . We will be using this new aproach for 3x new facility additions.

**Comment by ojwanganto** [comment]
Does this also factor in MFL codes?

**Comment by makombe** [comment]
> Does this also factor in MFL codes?

Yes the MFL is in there eg.`30550` is an mfl code in there.

**Comment by ojwanganto** [comment]
This approach is sustainable. Should we then make sure that we only install locations from the CSV if it's first time setup? That would mean to transition the processing to a chore

**Review by donaldkibet — APPROVED** [review]
@ojwanganto do you have any reservation on this approach. Would like to prepare for a patch and would like this to be part of it

**Comment by ojwanganto** [comment]
> @ojwanganto do you have any reservation on this approach. Would like to prepare for a patch and would like this to be part of it

No, I don't.

**Pull request merged**
