### PR TITLE
(feat) : add more special clinics

### PR DESCRIPTION
**Pull request by donaldkibet**
### Description

Add more special clinics as guided by @mmatheka. We might need to come up with a design to make special clinic section UX better given we have many.

**DONOT MERGE**

@mmatheka will need to provide encounter types for the special clinic form to avoid having on encounter type shared across many forms

### CODE REVIEW

**Comment by makombe** [comment]
Thanks @donaldkibet  I will find time to create the encounter types.

**Comment by ojwanganto** [comment]
Where did we get the encounter type UUIDs in the configurations? We should prioritize this

**Comment by mmatheka** [comment]
https://github.com/palladiumkenya/openmrs-module-kenyaemr/pull/1998/commits/3cf17b5eda1daccbcc9d4e7fee7a3526a3c9e2f6
@donaldkibet here is the PR that Makombe created with the  form encounters

**Comment by donaldkibet** [comment]
@mmatheka we don't have forms for MOPC and Oncology schema

**Comment by donaldkibet** [comment]
@RAJABIBRAZ merging this in for your testing
Deployed a version to dev instance cc @palladiumkenya/qa

**Comment by mmatheka** [comment]
@donaldkibet I have addressed the Oncology schema. @ckote is addressing the MOPC. Thanks.

**Pull request merged**
